name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
env:
  PROJECT_DIR: ''
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Find project directory
      id: find-dir
      run: |
        # Find the first directory matching 'lab*' or 'hw*'
        PROJECT_DIR=$(find . -maxdepth 1 -type d \( -name "lab*" -o -name "hw*" \) | head -n 1)
        if [ -z "$PROJECT_DIR" ]; then
          echo "No matching directory found!" >&2
          exit 1
        fi
        echo "PROJECT_DIR=${PROJECT_DIR}" >> $GITHUB_ENV
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '21'
    - name: sum_the_scores_in_input1
      id: unit-test-1
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: sum_the_scores_in_input1
        setup-command: ''
        command: "./gradle-tests/gradlew test --tests org.test.ClassTest.sum_the_scores_in_input1 -p gradle-tests"
        timeout: 10
        max-score: 20
    - name: sum_the_scores_in_input2
      id: unit-test-2
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: sum_the_scores_in_input2
        setup-command: ''
        command: "./gradle-tests/gradlew test --tests org.test.ClassTest.sum_the_scores_in_input2 -p gradle-tests"
        timeout: 10
        max-score: 20
    - name: throws_ioexception_when_input_file_not_found
      id: unit-test-3
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: throws_ioexception_when_input_file_not_found
        setup-command: ''
        command: "./gradle-tests/gradlew test --tests org.test.ClassTest.throws_ioexception_when_input_file_not_found -p gradle-tests"
        timeout: 10
        max-score: 20
    - name: throws_ioexception_when_output_file_not_writable
      id: unit-test-4
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: throws_ioexception_when_output_file_not_writable
        setup-command: ''
        command: "./gradle-tests/gradlew test --tests org.test.ClassTest.throws_ioexception_when_output_file_not_writable -p gradle-tests"
        timeout: 10
        max-score: 20
    - name: throws_ioexception_when_input_file_is_empty
      id: unit-test-5
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: throws_ioexception_when_input_file_is_empty
        setup-command: ''
        command: "./gradle-tests/gradlew test --tests org.test.ClassTest.throws_ioexception_when_input_file_is_empty -p gradle-tests"
        timeout: 10
        max-score: 20
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        UNIT-TEST-1_RESULTS: "${{ steps.unit-test-1.outputs.result }}"
        UNIT-TEST-2_RESULTS: "${{ steps.unit-test-2.outputs.result }}"
        UNIT-TEST-3_RESULTS: "${{ steps.unit-test-3.outputs.result }}"
        UNIT-TEST-4_RESULTS: "${{ steps.unit-test-4.outputs.result }}"
        UNIT-TEST-5_RESULTS: "${{ steps.unit-test-5.outputs.result }}"
      with:
        runners: unit-test-1,unit-test-2,unit-test-3,unit-test-4,unit-test-5
